# Generated by Django 3.0.4 on 2020-06-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200626_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(default='', max_length=1000)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
